name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: npm run build

      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: Debug build output
        run: |
          echo "Listing contents of the root directory..."
          ls -la
          echo "Listing contents of the dist directory..."
          ls -R dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Option 1: Use the built-in GitHub token (recommended)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Option 2: If you prefer your personal token, use this instead:
          # personal_token: ${{ secrets.GH_PAT }}

          publish_dir: ./dist
          cname: jbcnstars.com
          force_orphan: true
